twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
#        - 'form_error/my_form_error.html.twig'
        - 'bootstrap_5_layout.html.twig'

when@test:
    twig:
        strict_variables: true
