vich_uploader:
    db_driver: orm

    mappings:
        cours:
            uri_prefix: /documents/cours
            upload_destination: '%kernel.project_dir%/public/documents/cours'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true